[project]
name = "hr-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.116.2",
    "psycopg2>=2.9.10",
    "sqlmodel>=0.0.25",
    "uvicorn>=0.35.0",
]
